server:
  port: 8717

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Eric1230
    url: jdbc:mysql://localhost:3306/nowcoder_db?createDatabaseIfNotExist=true