server:
  port: 8717
  servlet:
    context-path: /nowcoder

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Eric1230
    url: jdbc:mysql://localhost:3306/nowcoder_db?createDatabaseIfNotExist=true
  mail:
    host: smtp.sina.com
    port: 465
    username:
    password:
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 0
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer: #生产者配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: #消费者配置
      group-id: nowcoder-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


nowcoder:
  path:
    domain: http://localhost:8717/nowcoder
    upload:
      header: /upload/header

logging:
  level:
    com.wavecom.nowcoder: debug