server:
  port: 8717
  servlet:
    context-path: /nowcoder

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Eric1230
    url: jdbc:mysql://localhost:3306/nowcoder_db?createDatabaseIfNotExist=true
  mail:
    host: smtp.sina.com
    port: 465
    username:
    password: 
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

nowcoder:
  path:
    domain: http://localhost:8717/nowcoder
    upload:
      header: /upload/header

logging:
  level:
    com.wavecom.nowcoder: debug